name: MCEngineBackPack
version: ${version}
main: io.github.mcengine.spigotmc.backpack.MCEngineBackPack
author: MCEngine
description: MCEngine BackPack
api-version: 1.18
softdepend: [HeadDatabaseAPI]
commands:
  backpack:
    description: Gives a player a backpack.
    usage: /backpack <create || get > <hdb id || head name> <size>